Document: paho.mqtt.python
Title: Debian paho.mqtt.python Manual
Author: <insert document author here>
Abstract: This manual describes what paho.mqtt.python is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/paho.mqtt.python/paho.mqtt.python.sgml.gz

Format: postscript
Files: /usr/share/doc/paho.mqtt.python/paho.mqtt.python.ps.gz

Format: text
Files: /usr/share/doc/paho.mqtt.python/paho.mqtt.python.text.gz

Format: HTML
Index: /usr/share/doc/paho.mqtt.python/html/index.html
Files: /usr/share/doc/paho.mqtt.python/html/*.html
